### ISSUE TITLE
Image component breaks blog overview

### ISSUE THREAD

**Issue by gonzalezmorales** [UNDataForum/main-website#39]
There is an issue with the react image component that prevents to display the first paragraph of a blog in the blog overview...

https://main-website.undataforum.now.sh/blog/

![image](https://user-images.githubusercontent.com/7047819/63382194-3681c480-c368-11e9-9a38-759b69ee9b2e.png)

**Comment by 454de6e** [comment]
@gonzalezmorales Good catch! The regex determines 1st para through empty lines. Will makes this a little more smart to factor in the import statement.

**Comment by 454de6e** [comment]
Needs to be fixed in the underlying theme, see https://github.com/UNDataForum/gatsby-themes/issues/86.

**Comment by 454de6e** [comment]
Fixed with https://github.com/UNDataForum/gatsby-themes/issues/86. Fix will be applied on next theme update.
